config/routes.rb
Rails.application.routes.draw do

 
  resources :news do
    resources :comments
  end
 
  
  

  get 'abouts/display'

  get "/newcomments" => "comments#index"
  
  get "/login" => "login#index"
  
  get "/submit" => "news#new"

  post 'sessions/create'

  post 'user/create'
  
  delete "logout" => "sessions#logout", :as => "logout"
  
  get 'news/next'
  
  root 'login#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :news
  validates :body, presence:true,length:{maximum: 1000, minimum: 3},format:{with: /\S{3,}/}
  default_scope -> {order(created_at: :desc)}
end

app/models/news.rb
class News < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  default_scope -> {order(created_at: :desc)}
  validates :title, presence:true,length:{maximum: 200,minimum:10}
  validates :url,allow_blank: true ,format:{with: /(https?:\/\/).([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?/}
   
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :news
    has_many :comments
    has_secure_password
     validates :name, presence:true, length:{maximum: 15, minimum: 2},format:{with: /[a-z\d]+[-_]/},uniqueness: { case_sensitive: false }
     validates :password, presence:true, length:{minimum: 10},format:{with: /(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[-,.?:;'"!_=+]).{10,}/}
    
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def display
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def login(user)
    session[:user_id] = user.id
  end
  
  def current_user
      @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    current_user.nil? ? false : true
  end
  

  
  
# private

#   def require_login
#     unless logged_in?
#       flash[:error] = "You must be logged in to access this section"
#       redirect_to :login_index # halts request cycle
#     end
#   end
  helper_method :current_user, :logged_in? 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_comment, only: [:show, :edit, :update, :destroy]



  NEWS_PER_PAGE=3
  # GET /comments
  # GET /comments.json
  def index
    # @comments = Comment.all
    @comments = Comment.order(:id).limit(NEWS_PER_PAGE) 
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
     @comment = Comment.find(params[:id])
     @user = @comment.find(params[:comment_id])
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    
    if logged_in?
      @news = News.find_by(params[:id])
      @comment = @news.comments.build(comment_params)
      @comment.user = current_user
    
      respond_to do |format|
        if @comment.save
          flash[:success] = "Successful commented"
          format.html { redirect_to @news}
          format.json { render :show, status: :created, location: @comment }
        else
          flash[:success] = "Input is too long or short"
          format.html { redirect_to @news }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    else
      flash[:success] = "Please log in first"
      redirect_to login_path
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  # def update
  #   respond_to do |format|
  #     if @comment.update(comment_params)
  #       format.html { redirect_to @comment }
  #       format.json { render :show, status: :ok, location: @comment }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @comment.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /comments/1
  # # DELETE /comments/1.json
  # def destroy
  #   @comment.destroy
  #   respond_to do |format|
  #     format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body)
    end
    
    
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
    @user = User.new
  end
end

app/controllers/news_controller.rb
require 'uri'



class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]
  before_filter :set_page, only: [:index]
  before_filter :set_title
  
  NEWS_PER_PAGE=8
  # GET /news
  # GET /news.json
  def index
    @news = News.order(:id).limit(NEWS_PER_PAGE).offset(@page * NEWS_PER_PAGE) 
    # @news = News.all
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @news = News.find(params[:id])
    @comments = @news.comments
  end

  # GET /news/new
  def new
    if logged_in?
      @news = News.new
    else
      flash[:success] = "Please log in first"
      redirect_to login_path
    end
  end

  # GET /news/1/edit
  def edit
  end
  
  # def next
  #   page = params[:page]
  #   params[:page] += 1
  #   @news = news.find_news_on_page(page, NEWS_PER_PAGE)
  #   render :new
  # end
  # POST /news
  # POST /news.json
  def create
    @news = current_user.news.new(news_params)

    respond_to do |format|
      if @news.save
         flash[:success] = "Successfully posted"
        format.html { redirect_to @news }
        format.json { render :show, status: :created, location: @news }
      else
         flash[:success] = "Something goes wrong"
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  # def update
  #   respond_to do |format|
  #     if @news.update(news_params)
  #       format.html { redirect_to @news, notice: 'News was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @news }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @news.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /news/1
  # DELETE /news/1.json
  # def destroy
  #   @news.destroy
  #   respond_to do |format|
  #     format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :url)
    end
    
    def set_page
       @page = params[:page].to_i || 0
    end
    
    def set_title
      @page_title = "Home Page #" + @page.to_s
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
     
  end
 
 def create
  # user = User.find_by(name: user_params[:name]).try(:authenticate, user_params[:password])
  user = User.find_by(name: user_params[:name])
  if user && user.authenticate(user_params[:password])
    login(user)
   flash[:success] = "Welcome to the Rmit News!"
   redirect_to login_path
  else
   flash[:success] = "invalid username or password"
    redirect_to login_path
  end
  
  
  def logout
    flash[:success] = "You have logged out."
    session[:user_id] = nil
    redirect_to login_path
  end
  
 
  
 end
 
 private
  def user_params
   params.require(:session).permit(:name, :password)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
  @user = User.new
  end
 
 def create
  @user = User.new(user_params)
  if @user.save
    login(@user)
   flash[:success] = "Welcome to the Rmit News!"
   redirect_to login_path
  else
   flash[:success] = "Fails to match the validation."
   redirect_to login_path
  end
 end
 
 private
  def user_params
   params.require(:user).permit(:name, :password)
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def title(page_title)
        content_for :title, page_title.to_s
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/abouts/display.html.erb
<h1>Group member</h1><hr>
<p>Quan Fan s3516995</p>
<p>Yue Li   s3538075</p>

<h1>Heroku deployed URL</h1><hr>
<%= link_to 'https://ancient-bayou-49438.herokuapp.com/', "https://ancient-bayou-49438.herokuapp.com/" %>

<h1>Assignment 2 Bitbucket URL</h1><hr>
<%= link_to 'https://bitbucket.org/QuanFan/rad18_assign_2_group_-s3516995_quan-fan-_-s3538075_yue-li/src/submission/', "https://bitbucket.org/QuanFan/rad18_assign_2_group_-s3516995_quan-fan-_-s3538075_yue-li/src/submission/" %>



app/views/comments/_form.html.erb
<%= form_for([@news, @news.comments.build]) do |f| %>


  <div class="field">
    <%= f.label :body, "Type your comment here:" %><br>
    <%= f.text_area :body ,:id=>"textarea" %>
  </div>
  <div class="actions">
    <%= f.submit "Add comment" %>
  </div>
  
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<% title "New Comments" %>

<p id="notice"><%= notice %></p>



<table>
  <tbody>
    <% @comments.each do |comment| %>
      <div class="comindex container">
       <label> <%= comment.user.name %> <%= time_ago_in_words(comment.created_at) %> ago | on: <%= comment.news.title %></label><br>
        <strong><%= comment.body %></strong>
      </div>
    <% end %>
  </tbody>
</table>

<br>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>News:</strong>
  <%= @comment.news.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user.name %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  

    <div class="container">
      <div class="col-xs-12">
          <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= value %></div>
          <% end %>
      </div>
    </div>
    
    <div class="container">
       <div>
         <h1><%=image_tag("RMIT.jpg",:alter=>"RoR icon")%> RMIT News </h1>
         <h3><%= link_to 'Home', news_index_path %>
            <%= link_to 'Comments', newcomments_path %>
            <%= link_to 'Submit', submit_path %>
            <%= link_to 'Login', login_path %></h3>
       </div>
    </div>
 </div>
 
<%= yield %>
  <hr>
  <div class="container">
   <h4><%= link_to 'API', "https://github.com/pigfly/RMIT-CSIT-RAD/tree/master/2018_S1/assignment2" %> |
   <%= link_to 'About', abouts_display_path %></h4>
  </div>
</body>
</html>

app/views/login/index.html.erb
 <div class="container">
   <h1>Login</h1></h1>
<% if logged_in? %>
  <%= link_to "logout", logout_path, method: "delete" %>
<% else %>
  <%= form_for :session, url: :sessions_create do |f| %>
     
      <p>
        <%= f.label :name %>
        <%= f.text_field :name %>
      </p>
     
      <p>
        <%= f.label :password %>
        <%= f.password_field :password %>
      </p>
     
      <p><%= f.button "Log in" %></p>
      <%end%>
    
    <h1>Create Account</h1>
  
   
    <%= form_for @user, url: :user_create do |f| %>
      <p>
        <%= f.label :name %>
        <%= f.text_field :name %>
      </p>
     
      <p>
        <%= f.label :password %>
        <%= f.password_field :password %>
      </p>
     
      <p><%= f.button "Create" %></p>
    <% end %>
<% end %>

</div>

app/views/news/_form.html.erb
<div class="container">
  <h1>Submit your news here:</h1>
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title, placeholder: "Required" ,:id=> "textarea2"%>
  </div>
  <div class="field">
    <%= f.label "News source (optional)" %><br>
    <%= f.text_area :url,:id=>"textarea3" %>
  </div>
  <div class="actions">
    <% if logged_in? %>
      <%= f.submit "Submit" %>
    <% else %>
      <%= link_to 'Login', login_path %>
    <% end %>
  </div>
<% end %>
</div>

app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<% title @page_title %>
<p id="notice"><%= notice %></p>
<div class="newstable container" >
<table>

  <tbody>
    <% @news.each_with_index do |news,index| %>
      <div class="newsindex">
        <strong><%= index+1 %>.</strong>
        <strong><%= news.title %></strong>
        <strong><%= link_to URI.parse(news.url).host, "#{news.url}" %></strong><br>
        <p>by <%= news.user.name %> <%= time_ago_in_words(news.created_at) %> ago | <%= news.comments.count %><%= link_to ' comments', news %></p>
      </div>
    <% end %>
  </tbody>
</table>
<br>
  <button><%= link_to "more", news_index_path(page: @page + 1) %></button>
  </div>

app/views/news/new.html.erb
<% title "Submit a news" %>
<%= render 'form' %>

app/views/news/show.html.erb
<% title @news.title %>
<p id="notice"><%= notice %></p>
<div class="container">
<div class="newsindex">
       
     <p><strong><%= @news.title %> | <%= URI.parse(@news.url).host %></strong></p><br>
     <p>  by <%= @news.user.name %>  <%= time_ago_in_words(@news.created_at) %> ago | <%= @news.comments.count %> comments
    </p>
</div>      

<%= render '/comments/form' %>

<h2>List of comments</h2><hr>

<div><p>
    
<% @news.comments.each do |comment| %>
   <%= comment.user %>
   <%= comment.body %><br>
<% end %>
</p></div>
</div>
 

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>